using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KY_MES.Domain.V1.DTOs.InputModels
{

    public class AddDefectResponseModel
    {
        public AutoGeneratedSymptom autoGeneratedSymptom { get; set; }
        public int id { get; set; }
        public DateTime defectDate { get; set; }
        public string status { get; set; }
        public string passStatus { get; set; }
        public string materialName { get; set; }
    }
    public class AutoGeneratedSymptom
    {
        public int id { get; set; }
        public string symptomLabelName { get; set; }
        public string failureMessage { get; set; }
        public WipProcessStepHistory wipProcessStepHistory { get; set; }
        public string operatorUserLogin { get; set; }
    }
    public class WipProcessStepHistory
    {
        public int id { get; set; }
        public string routeStepName { get; set; }
        public string routeStepRouteName { get; set; }
        public string resourceResourceName { get; set; }
        public DateTime inQueueDateTime { get; set; }
        public DateTime startDateTime { get; set; }
        public DateTime arrivalDateTime { get; set; }
        public DateTime endDateTime { get; set; }
        public Status status { get; set; }
        public string userUserLogin { get; set; }
        public int processLoopCount { get; set; }
        public int loopCount { get; set; }
    }
    public class Status
    {
        public int value { get; set; }
        public string text { get; set; }
    }

}
