using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KY_MES.Domain.V1.DTOs.InputModels
{

    public class AddDefectResponseModel
    {
        public object AutoGeneratedSymptom { get; set; }
        public int Id { get; set; }
        public DateTime DefectDate { get; set; }
        public string Status { get; set; }
        public string PassStatus { get; set; }
        public string MaterialName { get; set; }
    }
}
